version: "3"

services:
  docnotifier:
    image: registry.logoper.socialcode.ru/docnotifier:latest
    restart: on-failure
    ports:
      - 2893:2893
    environment:
      - DOC_NOTIFIER_SERVICE_ADDRESS=0.0.0.0:2893
      - DOC_NOTIFIER_WATCHED_DIRS=./indexer/watcher
      - OCR_SERVICE_ADDRESS=http://dedoc:9091
      - OCR_SERVICE_MODE=logoper
      - DOC_SEARCHER_SERVICE_ADDRESS=http://docsearcher:2892
      - TOKENIZER_MODE=none
      - TOKENIZER_CHUNK_SIZE=800
      - TOKENIZER_CHUNK_OVERLAP=100
      - TOKENIZER_RETURN_CHUNKS=true
      - TOKENIZER_CHUNK_BY_SELF=false
      - TOKENIZER_TIMEOUT_SECONDS=300
      - TOKENIZER_SERVICE_ADDRESS=http://embeddings:8000
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == rb-ai2]
      update_config:
        parallelism: 1
        delay: 10s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2893/hello"]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - notifier:/indexer
    networks:
      - llm_network
      - dedoc_network

networks:
  llm_network:
    external: true
  dedoc_network:
    external: true

volumes:
  notifier:
