[logger]
Level="INFO"
FilePath="./logs/app.log"
EnableFileLog=false

[watcher]
Address="0.0.0.0:2893"
WatchedDirectories="./indexer/watcher"

[ocr]
Address="http://localhost:8004"
Mode="raw"
Timeout=300

[searcher]
Address="http://localhost:2892"
Timeout=300

[tokenizer]
Address="http://localhost:8001"
Mode="none"
ChunkSize=800
ChunkOverlap=100
ReturnChunks=false
ChunkBySelf=false
Timeout=30

[storage]
DriverName="postgres"
User="metabase"
Password="metabase"
Address="localhost"
Port=5432
DbName="documents"
EnableSSL="disable"
